echo "Registering"
SET ENVIRONMENT=Level1
SET AZURE_CLIENT_ID=
SET AZURE_SECRET=
SET AZURE_SUBSCRIPTION_ID=
SET AZURE_TENANT=

echo ENVIRONMENT = %ENVIRONMENT%
echo AZURE_CLIENT_ID = %AZURE_CLIENT_ID%
echo AZURE_SECRET = %AZURE_SECRET%
echo AZURE_SUBSCRIPTION_ID = %AZURE_SUBSCRIPTION_ID%
echo AZURE_TENANT = %AZURE_TENANT%

echo "Finished"
PAUSE
