#!/bin/sh
echo "Registering"
export ENVIRONMENT=level1
export AZURE_CLIENT_ID=
export AZURE_SECRET=
export AZURE_SUBSCRIPTION_ID=
export AZURE_TENANT=
export AZURE_SUBNET_ADDRESS_RANGE=10.100.0.0/24

echo ENVIRONMENT = $ENVIRONMENT
echo AZURE_CLIENT_ID = $AZURE_CLIENT_ID
echo AZURE_SECRET = $AZURE_SECRET
echo AZURE_SUBSCRIPTION_ID = $AZURE_SUBSCRIPTION_ID
echo AZURE_TENANT = $AZURE_TENANT
echo AZURE_SUBNET_ADDRESS_RANGE = $AZURE_SUBNET_ADDRESS_RANGE

echo "Finished"
